# Generated by Django 4.0.5 on 2022-06-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_posts_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='whatzapp',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
